### ISSUE TITLE
Update to spring-boot 3

### ISSUE THREAD

**Issue by pzienowicz** [cdimascio/swagger-spring-functional#35]
Hi @cdimascio!
Could you adjust this library to use spring-boot 3.0?
If this lib is not supported any more, just let me know.

**Comment by cdimascio** [comment]
@pzienowicz will get this updated to v3 spring boot

**Comment by cdimascio** [comment]
available in >v4.x.x

**Comment by pzienowicz** [comment]
Many thanks @cdimascio !
Please take a look into `Validator` class, in line 30 i 44 it uses `status` function from `ServerResponse`.
In spring 6 there is no `status(HttpStatus status)` function, you need to use `status(HttpStatusCode status)` instead.
Can you fix it?
